version: '3.4'

services:
  advertmanagementdb: 
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4
  
  brand.advertmanagement:
    image: ${DOCKER_REGISTRY-}brandadvertmanagement
    build:
      context: .
      dockerfile: Brand.AdvertManagement/Dockerfile

volumes:
   postgres_volume:
   pgadmin_data: 