version: '3.4'

services:
  advertmanagementdb: 
    image: mcr.microsoft.com/mssql/server
  
  brand.advertmanagement:
    image: ${DOCKER_REGISTRY-}brandadvertmanagement
    build:
      context: .
      dockerfile: Brand.AdvertManagement/Dockerfile
