version: '3.4'

services:
  advertmanagementdb: 
    container_name: advertmanagementdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123456
      - POSTGRES_DB=AdvertManagementDb2
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - ./csv/Adverts.csv:/tmp/csv/Adverts.csv
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=oguz.nalbant@test.com
      - PGADMIN_DEFAULT_PASSWORD=test123456
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  brand.advertmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=advertmanagementdb;Port=5432;Database=AdvertManagementDb2;User Id=admin;Password=admin123456;"
    ports:
      - "5000:80"
    
